### ISSUE TITLE
bouncer app

### ISSUE THREAD

**Issue by thedominantlord** [undefVariable/Ignite#5]
ROBLOX Username: TheDominantLord
Plug.DJ Username: EDM_IS_LOVE_EDM_IS_LIFE
Timezone: Pacific Standard Time

Are you active: Yes
Are you mature: Yes, but I don't use grammar, like ever
Do you know the rules: Yes
Do you accept the fact that Serpentar may demote you if you piss him off: Yes, and I don't need to piss him off to let it happen

**Comment by undefVariable** [comment]
Accepted. Grammar doesn't matter about 99.9% of the time.
