### ISSUE TITLE
Bouncer Application

### ISSUE THREAD

**Issue by iNextDev** [undefVariable/Ignite#7]
ROBLOX Username: iNextDev
Plug.DJ Username: iNextDev
Timezone: Eastern

Are you active: Very active on everyday
Are you mature: Most of the time yes.
Do you know the rules: Yes I have read the rules forum.
Do you accept the fact that Serpentar may demote you if you piss him off: Yes I highly accept.

**Comment by undefVariable** [comment]
Accepted.
